### ISSUE TITLE
Highlight current file on the Changed File List

### ISSUE THREAD

**Issue by gnuaha7** [pbu88/diffy#11]
Is it possible to mark differently the file being shown in the Diff?

<img width="358" alt="screen shot 2016-10-29 at 12 49 38 pm" src="https://cloud.githubusercontent.com/assets/2422016/19831372/4f61e3aa-9dd6-11e6-8023-65973b0842e4.png">

**Comment by pbu88** [comment]
Hi @gnuaha7 thanks for opening this. It would be actually very useful. Probably is closely related to #5 and both issues could be addressed in the same fix.

**Comment by pbu88** [comment]
Done by commits 98b4e5f and 85c153a. It will underline the currently opened file. Took some time to do it xD
