### ISSUE TITLE
file upload limit too low

### ISSUE THREAD

**Issue by timomayer** [pbu88/diffy#18]
there seems to be a file upload limit of 2MB set in the server. can you please make this upload limit configurable in the configuration?

**Comment by pbu88** [comment]
Could you please explain why you need this? Are you hosting diffy offline? (never actually thought about that possible use case) The limit is roughly a megabyte (less).

**Comment by timomayer** [comment]
we are hosting it offline yes. and we have some diffs which are larger then the actual limit and we can not upload this diffs

**Comment by timomayer** [comment]
@pbu88 just to be clear what do you mean with offline? we are hosting the tool online but self hosted (from your github repo). when i start it with npm start the buid in server seems to have a default upload limit of 2MB so i can not upload diffs >2mb and i need to do that.

**Comment by pbu88** [comment]
The restriction is in the code not in the server (afaik). It was was put it because at the time when it was developed, the library I use to parse/show the diff (`diff2html`) was getting stuck with such big diffs. I don't know if it will work well with big diffs now. The fix should be very straightforward, I haven't had time to do it. I'll try to get it done as soon as I have some time.

**Comment by pbu88** [comment]
@timomayer could you please share the error/message you get when you try to upload a big diff? I'm trying to figure out if is the app that is returning the error or if it's the web server where you are hosting it. Thanks

**Comment by lhwparis** [comment]
hey @pbu88 sorry for the late response. this limi is there on the diffy.org website too. try to upload a doff file with more then 1MB and you see the message " Error: File too big, sorry! " where can i change this limit?

**Comment by timomayer** [comment]
hey @pbu88 sorry for the late response. this limi is there on the diffy.org website too. try to upload a doff file with more then 1MB and you see the message " Error: File too big, sorry! " where can i change this limit?

**Comment by pbu88** [comment]
This is intended. Diffs bigger than a megabyte are huge and for the moment I prefer to not allow them. A patch to make this limitation configurable shouldn't be difficult to add. If you could submit a PR with it I'm happy to accept it.

**Comment by timomayer** [comment]
can you at least met me know where i have to change the limit so i can do it myself? thanks
