### ISSUE TITLE
npm run build is making trouble 

### ISSUE THREAD

**Issue by nitroxdeveloping** [pbu88/diffy#21]
When i run "npm run build" i get the following error:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle diffy@1.0.0~prebuild: diffy@1.0.0
6 silly lifecycle diffy@1.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle diffy@1.0.0~build: diffy@1.0.0
8 verbose lifecycle diffy@1.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle diffy@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\xampp\htdocs\diffy\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\WebEx\Productivity Tools;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Users\tmfr\AppData\Local\Microsoft\WindowsApps;C:\Users\tmfr\AppData\Roaming\npm;C:\Users\tmfr\AppData\Local\atom\bin
10 verbose lifecycle diffy@1.0.0~build: CWD: C:\xampp\htdocs\diffy
11 silly lifecycle diffy@1.0.0~build: Args: [ '/d /s /c',
11 silly lifecycle   'babel src/ -d build/src; babel tests/ -d build/tests' ]
12 silly lifecycle diffy@1.0.0~build: Returned: code: 2  signal: null
13 info lifecycle diffy@1.0.0~build: Failed to exec build script
14 verbose stack Error: diffy@1.0.0 build: `babel src/ -d build/src; babel tests/ -d build/tests`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid diffy@1.0.0
16 verbose cwd C:\xampp\htdocs\diffy
17 error Windows_NT 10.0.14393
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error diffy@1.0.0 build: `babel src/ -d build/src; babel tests/ -d build/tests`
22 error Exit status 2
23 error Failed at the diffy@1.0.0 build script 'babel src/ -d build/src; babel tests/ -d build/tests'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the diffy package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     babel src/ -d build/src; babel tests/ -d build/tests
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs diffy
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls diffy
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by pbu88** [comment]
Did you try running `npm install` first? A couple of modules have been upgraded.
