### ISSUE TITLE
Cannot run from docker: docker compose up fails with "Cannot find module './v2/SharedDiffRepository'"

### ISSUE THREAD

**Issue by jvmatl** [pbu88/diffy#23]
Hi, I'm unable to get either the master or v2_experimental branches to run under docker. If I run the tests, one of the tests fails, and if I just try to docker-compose up, it fails immediately complaining about a missing file. Am I doing somethign wrong? The instructions seem too simple to screw up...

Steps to reproduce::

**Tesseract:diffy jvm$ git status**
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

**Tesseract:diffy jvm$ git log -1**
commit ce2d43c6ee42cd4b558c4de997c73fba4d589c80 (HEAD -> master, origin/master, origin/HEAD)
Author: Paulo Bu <paulobu88@gmail.com>
Date:   Wed Aug 22 20:42:00 2018 +0200

    Add google analytic metrics

**Tesseract:diffy jvm$ docker version**
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true

**Tesseract:diffy jvm$ docker-compose --version**
docker-compose version 1.22.0, build f46880f

**Tesseract:diffy jvm$ docker-compose up --build**
Building web
Step 1/7 : FROM node:latest
 ---> c0cfd9444538
Step 2/7 : RUN mkdir -p /diffy
 ---> Using cache
 ---> efac452471e9
Step 3/7 : COPY package.json /diffy
 ---> Using cache
 ---> 49afbce5e946
Step 4/7 : WORKDIR /diffy
 ---> Using cache
 ---> 1881a22d08a7
Step 5/7 : RUN npm install
 ---> Using cache
 ---> f40f1481c2f3
Step 6/7 : EXPOSE 3000
 ---> Using cache
 ---> c5fbea9abdcc
Step 7/7 : CMD ["node", "/diffy/src/app.js"]
 ---> Using cache
 ---> 61f34420cacb
Successfully built 61f34420cacb
Successfully tagged diffy:latest
Starting diffy_db_1 ... done
Recreating diffy_web_1 ... done
Attaching to diffy_db_1, diffy_web_1
db_1   | 2018-09-05T02:07:05.236+0000 I CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
db_1   | 2018-09-05T02:07:05.240+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=65a453e3bf27
db_1   | 2018-09-05T02:07:05.240+0000 I CONTROL  [initandlisten] db version v4.0.1
db_1   | 2018-09-05T02:07:05.240+0000 I CONTROL  [initandlisten] git version: 54f1582fc6eb01de4d4c42f26fc133e623f065fb
db_1   | 2018-09-05T02:07:05.240+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
db_1   | 2018-09-05T02:07:05.240+0000 I CONTROL  [initandlisten] allocator: tcmalloc
db_1   | 2018-09-05T02:07:05.240+0000 I CONTROL  [initandlisten] modules: none
db_1   | 2018-09-05T02:07:05.240+0000 I CONTROL  [initandlisten] build environment:
db_1   | 2018-09-05T02:07:05.240+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
db_1   | 2018-09-05T02:07:05.240+0000 I CONTROL  [initandlisten]     distarch: x86_64
db_1   | 2018-09-05T02:07:05.241+0000 I CONTROL  [initandlisten]     target_arch: x86_64
db_1   | 2018-09-05T02:07:05.241+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
db_1   | 2018-09-05T02:07:05.242+0000 W STORAGE  [initandlisten] Detected unclean shutdown - /data/db/mongod.lock is not empty.
db_1   | 2018-09-05T02:07:05.245+0000 I STORAGE  [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
db_1   | 2018-09-05T02:07:05.249+0000 W STORAGE  [initandlisten] Recovering data from the last clean checkpoint.
db_1   | 2018-09-05T02:07:05.250+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1461M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
**web_1  | internal/modules/cjs/loader.js:583
web_1  |     throw err;
web_1  |     ^
web_1  |
web_1  | Error: Cannot find module './v2/SharedDiffRepository'**
web_1  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
web_1  |     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
web_1  |     at Module.require (internal/modules/cjs/loader.js:637:17)
web_1  |     at require (internal/modules/cjs/helpers.js:20:18)
web_1  |     at Object.<anonymous> (/diffy/src/app.js:15:33)
web_1  |     at Module._compile (internal/modules/cjs/loader.js:689:30)
web_1  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
web_1  |     at Module.load (internal/modules/cjs/loader.js:599:32)
web_1  |     at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
web_1  |     at Function.Module._load (internal/modules/cjs/loader.js:530:3)
diffy_web_1 exited with code 1
db_1   | 2018-09-05T02:07:12.242+0000 I STORAGE  [initandlisten] WiredTiger message [1536113232:242882][1:0x7f6a0626aa00], txn-recover: Main recovery loop: starting at 2/256
db_1   | 2018-09-05T02:07:12.265+0000 I STORAGE  [initandlisten] WiredTiger message [1536113232:265217][1:0x7f6a0626aa00], txn-recover: Recovering log 2 through 3
db_1   | 2018-09-05T02:07:12.571+0000 I STORAGE  [initandlisten] WiredTiger message [1536113232:571520][1:0x7f6a0626aa00], file:index-3-4702602354184604668.wt, txn-recover: Recovering log 3 through 3
db_1   | 2018-09-05T02:07:12.617+0000 I STORAGE  [initandlisten] WiredTiger message [1536113232:617202][1:0x7f6a0626aa00], file:index-3-4702602354184604668.wt, txn-recover: Set global recovery timestamp: 0
db_1   | 2018-09-05T02:07:12.633+0000 I RECOVERY [initandlisten] WiredTiger recoveryTimestamp. Ts: Timestamp(0, 0)
db_1   | 2018-09-05T02:07:12.655+0000 I CONTROL  [initandlisten]
db_1   | 2018-09-05T02:07:12.655+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
db_1   | 2018-09-05T02:07:12.655+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
db_1   | 2018-09-05T02:07:12.655+0000 I CONTROL  [initandlisten]
db_1   | 2018-09-05T02:07:12.671+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
db_1   | 2018-09-05T02:07:12.673+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
db_1   | 2018-09-05T02:07:13.007+0000 I FTDC     [ftdc] Unclean full-time diagnostic data capture shutdown detected, found interim file, some metrics may have been lost. OK

**Tesseract:diffy jvm$ docker-compose run web npm test**
Starting diffy_db_1 ... done

> diffy@1.0.0 test /diffy
> sh run-tests.sh

> diffy@1.0.0 v2_build /diffy
> rm -r dist;tsc

  Diff
    #Diff()
      ✓ diff object should have rawDiffString field
      ✓ should generate array of two diff file objects
    #getRawDiff()
      ✓ should return the raw diff text

  DiffFile
    #getDeletedLines()
      ✓ should return 0
    #getAddedLines()
      ✓ should return 1
    #getNewFileName()
      ✓ should return package.json
    #getOldFileName()
      ✓ should return package.json

  SharedDiff
    #SharedDiff()
      ✓ should set up all the necessary fields

  Config Tests
    ✓ should read analytics key from env

  FileTree
    #new FileTree()
      ✓ path should be the root (/)
      ✓ should not have dirs
      ✓ should not have files
    #insert('test.txt')
      ✓ path should be the root (/)
      ✓ should not have any dirs
      ✓ should have one file
      ✓ should be named test.txt
    #insert('test.txt', {<arbitrary object>})
      ✓ path should be the root (/)
      ✓ should not have any dirs
      ✓ should have one file
      ✓ should be named test.txt
    #insert('test/test.txt')
      ✓ path should be the root (/)
      ✓ should have one dir
      ✓ should not have files
      ✓ should have one file in the subdir
      ✓ file should be named test.txt
    #insert() multiple times
      ✓ root should have one dir
      ✓ root should have 0 files
      subtree
        ✓ subtree should have two dirs
        ✓ subtree should have 0 files
        ✓ subtree path should be dir/subdir
      subsubtree
        ✓ should have 0 dirs
        ✓ should have 2 files
        ✓ should have path equals to subsubdir
        ✓ should have 2 files named file.php and file1.php
      subsubtree1
        ✓ should have 0 dirs
        ✓ should have 2 files
        ✓ should have path equals to subsubdir1
        ✓ should have 2 files named file.js and file1.js
    #insert() multiple levels
      ✓ subtree must have 3 files on level 0 dir
      ✓ subtree1 must have 3 files on level 1 dir
      ✓ subtree2 must have 3 files on level 2 dir
    #getFileName()
      ✓ should return the full name for a file

  Utils module
    #getFileName()
      ✓ should return new name
      ✓ should return old name if file is deleted
    #sortByFilenameCriteria()
      ✓ filename a is lower than filename b
      ✓ filename b is greater than filename a
      ✓ files with same filename should be equal
    **#genRandomString()
      1) should return a string of length greater or equal to 20**
    #isObjectEmpty()
      ✓ should return true for {}
      ✓ should return false for non empty object
    #exceedsFileSizeLimit()
      ✓ should return true for files of size 1000001
      ✓ should return false for files of size 1000000
      ✓ should return false for files of size less than 999999

  52 passing (68ms)
  1 failing

  **1) Utils module #genRandomString() should return a string of length greater or equal to 20:

      AssertionError: expected 'chldrcie2d' to have a length at least 20 but got 10
      + expected - actual

      -10
      +20**

      at Context.it (dist/tests/utils.js:57:60)

npm ERR! Test failed.  See above for more details.

**Comment by pbu88** [comment]
Hi @jvmatl thank you for filling such a detailed issue report. @omederos is looking into the docker issue. We'll get back at you once we figure it out.

**Comment by pbu88** [comment]
Hi @jvmatl. The latest three commits should've fixed the issue plus documented the new way of building the project. The Dockerfile was outdated. Can you test it? Thanks!

**Comment by pbu88** [comment]
The test still fails on docker for some reason. I'll investigate it as well.

**Comment by jvmatl** [comment]
Yep, test still fails for me, too, but I *can* run the app locally now with `docker-compose up`. 

Progress! :)

**Comment by pbu88** [comment]
For me the issue was more to fix Docker here. I don't develop with it that's why it got stale (maybe I should start doing it :-) ). I'm gonna close this issue and probably create a new one with the test failing inside docker (I recall is a platform specific or version specific issue, on Mac the test pass). A pull request with a fix would be great ;-) Thanks for reporting @jvmatl
