### ISSUE TITLE
Cannot drag and select code

### ISSUE THREAD

**Issue by tisaconundrum2** [pbu88/diffy#29]
When I want to copy a portion of code I find that the whole webpage will refresh and I lose the selection. I am pretty sure that it has to do with the timer at the top.

• Scanning the clock will not elicit this effect
• scanning code will deselect text

**Comment by pbu88** [comment]
Yes, this bug is almost fixed. It has to do with the angular component refreshing the whole text every second rather than just the clock, indeed. I'll try to get that fix in soon. I have not time to work on this tool for a while :-/ Need some fixes and obvious features indeed.

**Comment by pbu88** [comment]
This should be fixed now. The problem now is that the selection is not very good, it also selects line numbers and +/- signs but that's another fix. If you need it please submit another issue.
