### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by NicoWeio** [pbu88/diffy#33]
@pbu88 
The Let's Encrypt SSL certificate for _diffy.org_ has expired. Are you aware of this?
([See this link.](https://www.sslshopper.com/ssl-checker.html#hostname=https://diffy.org/))

**Comment by pbu88** [comment]
Hey @NicoWeio , thanks for reporting. I was unaware. I guess I missed the letsencrypt email warning me about it. It is fixed now.
