### ISSUE TITLE
Buttons do nothing

### ISSUE THREAD

**Issue by robhol** [pbu88/diffy#38]
Neither button does anything. I can't see anything in the console.
I'm on Vivaldi (Chrome-like)

**Comment by pbu88** [comment]
The site is back up. The local db had a small glitch. There was indeed no feedback at all what the problem was, just unresponsiveness. Should improve that. Thanks for letting me know.

**Comment by pbu88** [comment]
Hey, very old Issue but just letting you know the error handling has been improved and it should be better now :-)
