### ISSUE TITLE
[feature request] select text from diff without line numbers and "+"

### ISSUE THREAD

**Issue by leoleoasd** [pbu88/diffy#53]
![image](https://user-images.githubusercontent.com/37735580/124908609-128f0100-e01c-11eb-9a33-54e4c37f7351.png)
maybe simply upgrade "diff2html" library will do this?

the demo of the latest diff2html library handles this well.
![image](https://user-images.githubusercontent.com/37735580/124908683-2dfa0c00-e01c-11eb-94a5-96621260899e.png)

**Comment by pbu88** [comment]
Hey, thanks for submitting. I will do the update as soon as I get some free time.

**Comment by BabyLoves** [comment]
> Hey, thanks for submitting. I will do the update as soon as I get some free time.

Please, make it on diffy.org > , <

**Comment by pbu88** [comment]
Haven't found the time to get it done but will push it to do it before next wekk.

**Comment by pbu88** [comment]
Hi, this problem should have been fixed. I upgraded to the latest version of diff2html and it worked out of the box: 
![image](https://user-images.githubusercontent.com/3682272/130800575-6d8c34ea-aa64-4d38-9bc3-53df0fd978c2.png)

It is already rolled out, closing this ticket now.

**Comment by NicoWeio** [comment]
Here's the commit for reference: e2e565b2b4ee1b781b6e34ec375418f23046f964
