### ISSUE TITLE
provide an API

### ISSUE THREAD

**Issue by timomayer** [pbu88/diffy#6]
it would be cool if this tool could have a REST-API so you can do a post request with a diff file attached and get the unique URL to this diff as response.

**Comment by pbu88** [comment]
Hi @timomayer 

Thank you very much for submitting your recommendations. Much appreciated.

Luckily we already have that but I don't think I have not documented it :( (I need to do it)

We have an api endpoint `/api/new` that when you send a _diffy_ output in the `udiff` parameter it will generate a diff for you.

Using cURL you can do it like this: 
    curl -F "udiff=$(git diff)" https://diffy.org/api/new
    {"status":"success","url":"http://diffy.org/diff/9xumbfdrmnobhuxr"}

`url` is the generated diff page.

From node you can use it like this:

```
fs = require('fs');
request = require('request');
fs.readFile('x.diff', 'utf8', 
        function(e, d) {
            request.post(
                    'http://diffy.org/api/new', 
                    {form: 
                        { udiff: d }
                    }, 
                    function(e, r, b) {
                        console.log(b);
                    });
        });
```

Where `x.diff` is _diffy_ file.

Hope this helps! I need to include this in the docs!!.

**Comment by timomayer** [comment]
thanks a lot for your help. i ll test it within the following days :)

**Comment by pbu88** [comment]
Closing for now since the basic API is there. There are plans to improve it a bit though that will be addressed as a different issue.
