### ISSUE TITLE
Unable to load any diffs on diffy.org

### ISSUE THREAD

**Issue by c3-BrettThompson** [pbu88/diffy#74]
Any `git diff` I have either copy/pasted into the text box or uploaded has been failing with:

"oops, something went wrong ... "

**Comment by pbu88** [comment]
Indeed looks like something is broken server side. I have limited access to a computer at the moment. Will try to fix as soon as I can.

**Comment by c3-BrettThompson** [comment]
Yes, it have been fixed for awhile now.  Sorry, should have updated the ticket.

Thank you for the quick turn around!  Really love this tool.
