### ISSUE TITLE
SSL certificate expired

### ISSUE THREAD

**Issue by NicoWeio** [pbu88/diffy#88]
As you can verify [here](https://www.sslshopper.com/ssl-checker.html#hostname=diffy.org), the _Let's Encrypt_ certificate of https://diffy.org has expired a few days ago. @pbu88, please update it. :)

**Comment by pbu88** [comment]
Thanks for reaching out. Fixed! I need to automate this, it happens quite often.

**Comment by NicoWeio** [comment]
Thank you!
I don't know much about automatic renewal, but you could set up uptimerobot.com for free to get reminders about expiring certificates.
