### ISSUE TITLE
https://diffy.org/ 's certificate is expired

### ISSUE THREAD

**Issue by mhtocs** [pbu88/diffy#90]
![image](https://github.com/pbu88/diffy/assets/16911901/94ede4ec-69d1-4774-8e47-cb759c02feee)

![image](https://github.com/pbu88/diffy/assets/16911901/39c43c5d-4f23-4d14-b731-e26cf41c1548)

**Comment by pbu88** [comment]
Fixed. Thanks for the heads up!

**Comment by KaKi87** [comment]
And again !

Please implement automated renewal.

Or, at least, put a reminder on your calendar, because Let's Encrypt certificates expire every 3 months.
