### ISSUE TITLE
Error: Oops, something broke on the server :-/

### ISSUE THREAD

**Issue by baseballlover723** [pbu88/diffy#96]
Getting `Error: Oops, something broke on the server :-/` when trying to submit a new diff. It's been going on a few days and it also 500s when trying to load a diff as well (example diff from google: https://diffy.org/diff/b03c06683c17d) with the api call giving an error message of `oops, something went wrong ...`.

I'd guess it probably something similar to https://github.com/pbu88/diffy/issues/74 or https://github.com/pbu88/diffy/issues/71

**Comment by pbu88** [comment]
Sorry, the db server was down. Can you try again now? Thanks for letting me know, I need to automate monitoring on these things but dont really have time 😕

**Comment by baseballlover723** [comment]
It's working again, thanks!
